application: noteworthytunercom
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /styles
  static_dir: static/styles

- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /faq
  script: _go_app

- url: /changelog
  script: _go_app

- url: /sourcecode
  script: _go_app
